### ISSUE TITLE
Tablet and hover state - feature request

### ISSUE THREAD

**Issue by nicksturkenboom** [GaryJones/accessible-menu#1]
Hello Gary, I was discussing with Rob Neu how your menu isn't able to support hover events on tablet devices. I'm running some tests through the Chrome device emulator and expected to see a single tap triggering a hover event and the second tap a click event but this unfortunately isn't the case.

It would be a very welcoming feature to see tablet devices supporting hover events through your menu.

**Comment by GaryJones** [comment]
This is going to sound like a very poor Support answer, but I'd recommend using Superfish instead of my plugin here. It already has touch support built in, as well as a load of other features, and is used far more in the real world which should have eliminated most bugs.
